### Generate PGP Key Pair (Plain Text)
GET http://localhost:7071/api/generatePGPKeys

### Encrypt a Message (Public Key & Data in Body)
POST http://localhost:7071/api/pgpexample
Content-Type: text/plain

START PUBLIC KEY
-----BEGIN PGP PUBLIC KEY BLOCK-----

xsBNBGeu+aIBCADZyR5HqKNQkc0+cLDzuyFUpc33H6lvHVz7PfoCwNBeD4k4
9fF5hqEUwTl/uzOvufAfhXShqkn3lj629BgwdmYUYXR2JuQFAEtCC0Y8iO8Q
vHs6bT9v8WGbTHFIneU3ycUGS3aqxPZepCGgdBN6W5UqO7pEF0btRfXdEf/z
AJG4ihryRf7gpj/yOq7Wr2pmFFHIRcmpe9vBJx7D8UPDR+BsDhEI/VG4G+KI
kF03NkBTjtC2rFjVIx88KvdcNd+bCcpwKggRLiBmM4SFumCRLJxv1u5DIV/6
0y/+ImTw63RJwtoA75P+OWMSqGyXaY6zEzFQm3tLkVebRUJvUopOUQnLABEB
AAHNI0F6dXJlIEZ1bmN0aW9uIDxhenVyZUBmdW5jdGlvbi5jb20+wsDRBBMB
CgCFBYJnrvmiAwsJBwmQlZ4h01KYWUhFFAAAAAAAHAAgc2FsdEBub3RhdGlv
bnMub3BlbnBncGpzLm9yZ9si/NcpwI2Gb8FwZCfqJZ+TP4S0nc6AZmclDMBp
HjJ/BRUKCA4MBBYAAgECGQECmwMCHgEWIQR2FsEtBkbPwLps4N6VniHTUphZ
SAAAeQkH/305kZPuJYI5laST0/FpUQuHgquYr+ZWmxO60Cc/ghzSv4Tn5cbJ
8Q13TPMtfH114eIJaF18CcuJ939hYLz6jX2UnBOg0dgMRvod7txNXb3ufuIj
KraAXLDSolxnUQRmlqlQosbo1xBoeCVAD3tp7YBCIXKDDQluNpRyiCFd5oZV
mk2hMTEvBbVMF15ECluDbxewJkLQFfLM0BanLypheDl0QLkowYJxKoUeMXui
iqTLc7NXwSCzc1RVLq9dU904deLavgY9g2PwXwVO5eQVbeyZHwN+QATAVXTn
f83CCeAwuqDqmwVcU0Wxu1wNhKL15GT7R6wO4J3bG3DR3Wmy8nnOwE0EZ675
ogEIAMbISOXukrYfRIKQyRVQ92Z/n+V3n7oJKKsDK5SbCoCqkXJCOa9fi0JI
/J16nr+KhMVblWzRVEDEC2/MFGGR8sTMm+rfFFROOf7oX9TMTXHey8pCBOwH
E9tLDQMxgHbq+TT57b83LhmYmbfueVS8mJvq2RHROJFlQaR4VL2bOk71f9oB
gkBdGo7N/REtBXqD5VuhD0CHi2LkwwLIjyfdGS3xCLaS8kjxSBZjjwk8RO8M
KJEG+2ylhUxZHkYUQuO33eiemt3RobJO9ikYlkbPcnyX2DWrjs5aNsC/nfRb
faarjzfbWoCs4ZTAu2Lo9rfR3VS+wK/1snLMtQCzEGe0Zt0AEQEAAcLAvAQY
AQoAcAWCZ675ogmQlZ4h01KYWUhFFAAAAAAAHAAgc2FsdEBub3RhdGlvbnMu
b3BlbnBncGpzLm9yZ2Ywq2Xo4/3PUZ9TyStt/L9t2OuBl7ZDpFIeGU+R3BQx
ApsMFiEEdhbBLQZGz8C6bODelZ4h01KYWUgAABuVB/4oA6M5MrDU/2jywUi1
821vuiTZaFo7aL8Fg8Pi03S55IfN9pDDqLNGRCyBCx2g3wKElD9BHlzQHEG9
uJ825R40qsNaEz63eB3NJtmBeheL1yxD6D76z+gC7yFYNY3NRhMWWAu169oR
h8ZxRzxObup1BMChFNA2kx58WIC4vVQFOsgzYLLKQgf9AtsSgNYOXzo6uh/x
k6TPLKXGXDGIuhLyhX5+0NJyNoUiZtcOIzvX9iMPXmtSh5rTnT+ly/k5ZmF+
/Mr1qtG0thfrMPySRnKVtOHe8s4gJtF0rT0x/Okj4yNXLp2621ntSPuv86GP
Q+OzhluMEhtxmTiXRgDixPiv
=+5mh
-----END PGP PUBLIC KEY BLOCK-----
START DATA
Hello, encrypt me!

### Decrypt a Message (Private Key & Encrypted Message in Body)
POST http://localhost:7071/api/decryptPGP
Content-Type: text/plain

START PRIVATE KEY
-----BEGIN PGP PRIVATE KEY BLOCK-----

xcLYBGeu+aIBCADZyR5HqKNQkc0+cLDzuyFUpc33H6lvHVz7PfoCwNBeD4k4
9fF5hqEUwTl/uzOvufAfhXShqkn3lj629BgwdmYUYXR2JuQFAEtCC0Y8iO8Q
vHs6bT9v8WGbTHFIneU3ycUGS3aqxPZepCGgdBN6W5UqO7pEF0btRfXdEf/z
AJG4ihryRf7gpj/yOq7Wr2pmFFHIRcmpe9vBJx7D8UPDR+BsDhEI/VG4G+KI
kF03NkBTjtC2rFjVIx88KvdcNd+bCcpwKggRLiBmM4SFumCRLJxv1u5DIV/6
0y/+ImTw63RJwtoA75P+OWMSqGyXaY6zEzFQm3tLkVebRUJvUopOUQnLABEB
AAEAB/41XE80fI/DSm4Q6fiZR1Tj0ho0fgf8JyQklOtgaFDFcyYKlEwdnAx0
suE9OCdyW2sHtiG9CKXF6YSlPAp/OUtKnBQ2bNH6nbdSz8NeSqjUn3HL/3+H
FIv3SpQJGFLUx/Wj1LKXJdo9lxZ8I2SwWqciKW86hr+EnFsg1uuw5QdPQOeG
4etoNUTCZ3UKP+4jAjdGKVo35TJW7t1solC8+yVI4wv+ahu8aOm1sUszL1S2
lkCsFoQS8gq+vS2OEVzdEBStKe7OPf37SAHDI5M/BONVGb1nHSPiZg3w52KV
GHpuFriwe5gYCo0Qc82gjig7CarANqGTX1OTovkPAPXSUSWFBADiCU2irkqt
m1RzH23StuVe6RXbndw6gjZg+PPaq0V59XgdY1ybCbSm7F4WEt8eEMLtI/jG
PJvmNbY6jBZy4Hcf7UM8GPhkfEc070biNbAeEJ/3Sbv2C8e0pYt2H33n9JMj
+KGe1yMEWwMGsrqhcvukI7ikt+lKmSx18xfTzS17HwQA9qfSNm0o2bZSKpDw
OxDuM20A6KUU2Ek2U1n557jTRv/xXHR3gdzftcDlfdd65yWM0s3KQ7ZAZO1M
tW12buHbTBY13XbCI0w/+j57XPbAC5WqdizoBkJk8FuzgJ9VwNbIPxawNA1u
6gI8dDI3U/dSueeNmpegs7i+YnNhfw8sR9UD/RopeKL8uYIBl0F8kwOVtf29
Kmxt9nc6jV7WmWSFE8ZJEGLvfldumNe7O2/K1XQy1/khF8BJMKaUJGs2qOk/
3EGcsD950z64lY+HD6psSddm5rJjFiOQHiU7nJ6zM45/1sqsfmZTlBz6EQVf
jrF5eZN/VB1omoE1O+8myyVYCoEXOZPNI0F6dXJlIEZ1bmN0aW9uIDxhenVy
ZUBmdW5jdGlvbi5jb20+wsDRBBMBCgCFBYJnrvmiAwsJBwmQlZ4h01KYWUhF
FAAAAAAAHAAgc2FsdEBub3RhdGlvbnMub3BlbnBncGpzLm9yZ9si/NcpwI2G
b8FwZCfqJZ+TP4S0nc6AZmclDMBpHjJ/BRUKCA4MBBYAAgECGQECmwMCHgEW
IQR2FsEtBkbPwLps4N6VniHTUphZSAAAeQkH/305kZPuJYI5laST0/FpUQuH
gquYr+ZWmxO60Cc/ghzSv4Tn5cbJ8Q13TPMtfH114eIJaF18CcuJ939hYLz6
jX2UnBOg0dgMRvod7txNXb3ufuIjKraAXLDSolxnUQRmlqlQosbo1xBoeCVA
D3tp7YBCIXKDDQluNpRyiCFd5oZVmk2hMTEvBbVMF15ECluDbxewJkLQFfLM
0BanLypheDl0QLkowYJxKoUeMXuiiqTLc7NXwSCzc1RVLq9dU904deLavgY9
g2PwXwVO5eQVbeyZHwN+QATAVXTnf83CCeAwuqDqmwVcU0Wxu1wNhKL15GT7
R6wO4J3bG3DR3Wmy8nnHwtgEZ675ogEIAMbISOXukrYfRIKQyRVQ92Z/n+V3
n7oJKKsDK5SbCoCqkXJCOa9fi0JI/J16nr+KhMVblWzRVEDEC2/MFGGR8sTM
m+rfFFROOf7oX9TMTXHey8pCBOwHE9tLDQMxgHbq+TT57b83LhmYmbfueVS8
mJvq2RHROJFlQaR4VL2bOk71f9oBgkBdGo7N/REtBXqD5VuhD0CHi2LkwwLI
jyfdGS3xCLaS8kjxSBZjjwk8RO8MKJEG+2ylhUxZHkYUQuO33eiemt3RobJO
9ikYlkbPcnyX2DWrjs5aNsC/nfRbfaarjzfbWoCs4ZTAu2Lo9rfR3VS+wK/1
snLMtQCzEGe0Zt0AEQEAAQAH+wdsDQTAzquMKVOysj9ggYxLMZ4wxD7+/oy8
FpF65H5/X+TjQiIhMCLudLgwjuLZ+jEgRUkF2957M24eMZifCXB9r0iqwaiQ
LywsYv+gDTg2OGe55VMmxIAIoli/LWvDREDNICpmlgsQnpS2i8M1M4GG2EoJ
BNKw9C1+7LMTq66s/QK6x/oztw4OJ52WiyCHpo3Nmfsj2HlQgRRAjes52OaY
7qXXnboYC1n2q14+g9neOpOHGlG0d6hpylbO93z4k/shsf2q8DMRnQpDZmAG
qm9fYA8aREK5CdPwB/udNdVBSL6IpL8ZdQdn+5y1A6khaVW0Otig0DfLy11B
9LJwPeUEAMqkl1iOjjMmAUMqfJvHHrocOY6h5YLLC37iDVGAYCA4PaeHtMhK
ZbN2LpyI40Bp8HV6DBWl71mWAb4vbdDRAKwSoArgEKITAmsuNFJ+EgFPE8FL
dQ9z+f8eysI17e7ZZtUKokHF1pUft+SXxsBaxxN2B0fbnVTFxx8gWd0nnpn7
BAD7H3d64Tt4bw4KzDRC4T24HtoU4+h7V52Xvjg9yCdG9Uy5S4FpvKjufePV
bTcBwoKzo2kuS+ma1DcTBuztUcsTvIBhZfXy9nccaW0/WHsQ7OHIMTbgwN6/
UxbeFSLQWTwmDoeH3GXs9JAA4d/zZJEsgzi43teztm+mtuLh0PzDBwQAqdrp
7w94y1I9IisdVjU/skikDzs3H9wXRHf5v6dZltQbk7T0TjiDri208C39frZK
WfGYc8o2jbdl8WQ/kRzj95Z99cXYKR0XUVxOVBNF9p9Yl4wmtiafKbwBo0lX
QE/A8f6OY4kFWyv0Yk1SSdrqYbugSb517BRVpvixOmj1Czo8fsLAvAQYAQoA
cAWCZ675ogmQlZ4h01KYWUhFFAAAAAAAHAAgc2FsdEBub3RhdGlvbnMub3Bl
bnBncGpzLm9yZ2Ywq2Xo4/3PUZ9TyStt/L9t2OuBl7ZDpFIeGU+R3BQxApsM
FiEEdhbBLQZGz8C6bODelZ4h01KYWUgAABuVB/4oA6M5MrDU/2jywUi1821v
uiTZaFo7aL8Fg8Pi03S55IfN9pDDqLNGRCyBCx2g3wKElD9BHlzQHEG9uJ82
5R40qsNaEz63eB3NJtmBeheL1yxD6D76z+gC7yFYNY3NRhMWWAu169oRh8Zx
RzxObup1BMChFNA2kx58WIC4vVQFOsgzYLLKQgf9AtsSgNYOXzo6uh/xk6TP
LKXGXDGIuhLyhX5+0NJyNoUiZtcOIzvX9iMPXmtSh5rTnT+ly/k5ZmF+/Mr1
qtG0thfrMPySRnKVtOHe8s4gJtF0rT0x/Okj4yNXLp2621ntSPuv86GPQ+Oz
hluMEhtxmTiXRgDixPiv
=JWH7
-----END PGP PRIVATE KEY BLOCK-----
START ENCRYPTED MESSAGE
-----BEGIN PGP MESSAGE-----

wcBMA+cd7wPUFCp+AQgAi3ck1N+np8AlYT98qa0oupT+pdTQcTp/C+fVurJP
pmWejmt6C5mtfsD2YfjH/MPKIsvIR28L18xpBx0UdoXb0IITv4Q6iBVayotW
KnWE3rl59Qtp8Oka1z1nO3EGUwzICZgikthFbkIweCuWsyTVc/U2XrtMddQE
1oFuSo6IhtUOcK7ZLRQWAwR4vcdcksuAGGe4FbizQJxlCdAe+lAGZ22jfLSg
pgjNQ8zBmpNkviA/rKoeZclThOEjTC1XLBJ1vFG68edWSEzDJjU85mn25veG
0WWjOd6uNP5henr8q71yYgmfBqYPVDfo2Yx+S1PVxGq0OPVKlAber6/TnWXo
I9JDAdeCHiMojhrGUDH6876FVhTOms2Uc2emrQz5YqR/hv9leN3sX2/uRGvo
Aam2zgPrNBZD41z7Yy6D02JoPVhtZTLasQ==
=qB31
-----END PGP MESSAGE-----
